language: c
before_install:
  - wget https://gist.githubusercontent.com/petere/5893799/raw/apt.postgresql.org.sh
  - sudo sh ./apt.postgresql.org.sh
  - sudo rm -vf /etc/apt/sources.list.d/pgdg-source.list
script:
  - bash ./pg-travis-test.sh

env:
  # WARNING! UPGRADE_TO tests pg_upgrade; UDPATE_FROM tests ALTER EXTENSION! Note UPGRADE vs UPDATE!
  - UPGRADE_TO=9.2 PGVERSION=9.1
  - UPGRADE_TO=9.3 PGVERSION=9.2
  - UPGRADE_TO=9.4 PGVERSION=9.3
  - UPGRADE_TO=9.5 PGVERSION=9.4
  - UPGRADE_TO=9.6 PGVERSION=9.5
  - UPGRADE_TO=10  PGVERSION=9.6
  - UPGRADE_TO=11  PGVERSION=10
  - UPGRADE_TO=12  PGVERSION=11   UPDATE_FROM=0.99.0
  -                PGVERSION=12   UPDATE_FROM=0.99.0
  - UPGRADE_TO=12  PGVERSION=9.1
  # Duplication below is via s/-.*PGVERSION/- PARALLEL_CONN=1 PGVERSION/
  - PARALLEL_CONN=1 PGVERSION=9.1
  - PARALLEL_CONN=1 PGVERSION=9.2
  - PARALLEL_CONN=1 PGVERSION=9.3
  - PARALLEL_CONN=1 PGVERSION=9.4
  - PARALLEL_CONN=1 PGVERSION=9.5
  - PARALLEL_CONN=1 PGVERSION=9.6
  - PARALLEL_CONN=1 PGVERSION=10
  - PARALLEL_CONN=1 PGVERSION=11   UPDATE_FROM=0.99.0
  - PARALLEL_CONN=1 PGVERSION=12   UPDATE_FROM=0.99.0
script: bash ./pg-travis-test.sh
