# Copyright (c) YugaByte, Inc.
us-west-1:
  name: US West (N. California)
  latitude: 36.778261
  longitude: -119.417932
  availabilty_zones: [us-west-1a, us-west-1b, us-west-1c]
us-west-2:
  name: US West (Oregon)
  latitude: 43.804133
  longitude: -120.554201
  availabilty_zones: [us-west-2a, us-west-2b, us-west-2c, us-west-2d, us-west-2-den-1a, us-west-2-las-1a, us-west-2-lax-1a, us-west-2-lax-1b, us-west-2-sea-1a]
us-east-1:
  name: US East (N. Virginia)
  latitude: 37.478397
  longitude: -76.453077
  availabilty_zones: [us-east-1a, us-east-1b, us-east-1c, us-east-1d, us-east-1e, us-east-1f, us-east-1-atl-1a]
us-east-2:
  name: US East (Ohio)
  latitude: 40.367474
  longitude: -82.996216
  availabilty_zones: [us-east-2a, us-east-2b, us-east-2c]
eu-west-1:
  name: Europe (Ireland)
  latitude: 53.412910
  longitude: -8.243890
  availabilty_zones: [eu-west-1a, eu-west-1b, eu-west-1c]
eu-central-1:
  name: Europe (Frankfurt)
  latitude: 50.110922
  longitude: 8.682127
  availabilty_zones: [eu-central-1a, eu-central-1b, eu-central-1c]
ap-southeast-1:
  name: Asia Pacific (Singapore)
  latitude: 1.352083
  longitude: 103.819836
  availabilty_zones: [ap-southeast-1a, ap-southeast-1b, ap-southeast-1c]
ap-northeast-1:
  name: Asia Pacific (Tokyo)
  latitude: 35.689487
  longitude: 139.691706
  availabilty_zones: [ap-northeast-1a, ap-northeast-1c, ap-northeast-1d]
ap-southeast-2:
  name: Asia Pacific (Sydney)
  latitude: -33.868820
  longitude: 151.209296
  availabilty_zones: [ap-southeast-2a, ap-southeast-2b, ap-southeast-2c]
sa-east-1:
  name: South America (Sao Paulo)
  latitude: -23.550520
  longitude: -46.633309
  availabilty_zones: [sa-east-1a, sa-east-1b, sa-east-1c]
eu-west-2:
  name: Europe (London)
  latitude: 51.5287718
  longitude: 0.2416806
  availabilty_zones: [eu-west-2a, eu-west-2b, eu-west-2c]
eu-west-3:
  name: Europe (Paris)
  latitude: 48.8589507
  longitude: 2.2770204
  availabilty_zones: [eu-west-3a, eu-west-3b, eu-west-3c]
ap-south-1:
  name: Asia Pacific (Mumbai)
  latitude: 19.0825223
  longitude: 72.7411014
  availabilty_zones: [ap-south-1a, ap-south-1b, ap-south-1c]
ap-south-2:
  name: Asia Pacific (Hyderabad)
  latitude: 17.3850
  longitude: 78.4867
  availabilty_zones: [ap-south-2a, ap-south-2b, ap-south-2c]
ca-central-1:
  name: Montreal (Canada)
  latitude: 45.5580421
  longitude: -73.7303025
  availabilty_zones: [ca-central-1a, ca-central-1b, ca-central-1c, ca-central-1d]
# TODO: not currently supported in x-region VPC.
ap-northeast-2:
 name: Asia Pacific (Seoul)
 latitude: 37.566535
 longitude: 126.977969
 availabilty_zones: [ap-northeast-2a, ap-northeast-2b, ap-northeast-2c, ap-northeast-2d]
# Location information compiled from
# https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/utils/geocoder
ap-northeast-3:
  name: Asia Pacific (Osaka)
  latitude: 34.693725
  longitude: 135.502254
  availabilty_zones: [ap-northeast-3a, ap-northeast-3b, ap-northeast-3c]
me-south-1:
  name: Middle East (Bahrain)
  latitude: 26.0667
  longitude: 50.5577
  availabilty_zones: [me-south-1a, me-south-1b, me-south-1c]
ap-east-1:
  name: Asia Pacific (Hong Kong)
  latitude: 22.319304
  longitude: 114.169361
  availabilty_zones: [ap-east-1a, ap-east-1b, ap-east-1c]
af-south-1:
  name: Africa (Cape Town)
  latitude: -33.924868
  longitude: 18.424055
  availabilty_zones: [af-south-1a, af-south-1b, af-south-1c]
eu-south-1:
  name: Europe (Milan)
  latitude: 45.464204
  longitude: 9.189982
  availabilty_zones: [eu-south-1a, eu-south-1b, eu-south-1c]
eu-north-1:
  name: Europe (Stockholm)
  latitude: 59.329323
  longitude: 18.068581
  availabilty_zones: [eu-north-1a, eu-north-1b, eu-north-1c]
us-gov-east-1:
  name: US Govt East (N. Virginia)
  latitude: 37.478397
  longitude: -76.453077
  availabilty_zones: [us-gov-east-1a, us-gov-east-1b, us-gov-east-1c]
us-gov-west-1:
  name: US Govt West (N. Virginia)
  latitude: 36.778261
  longitude: -119.417932
  availabilty_zones: [us-gov-west-1a, us-gov-west-1b, us-gov-west-1c]
ap-southeast-3:
  name: Asia Pacific (Jakarta)
  latitude: -6.200000
  longitude: 106.816666
  availabilty_zones: [ap-southeast-3a, ap-southeast-3b, ap-southeast-3c]
