# Copyright (c) YugaByte, Inc.
# az account list-locations -o table from Azure CLI
# Residency https://azure.microsoft.com/en-us/global-infrastructure/data-residency/

westus:
  name: West US
  latitude: 37.783
  longitude: -122.417
westus2:
  name: West US 2
  latitude: 47.233
  longitude: -119.852
westcentralus:
  name: West Central US
  latitude: 40.890
  longitude: -110.234
centralus:
  name: Central US
  latitude: 41.5908
  longitude: -93.6208
northcentralus:
  name: North Central US
  latitude: 41.8819
  longitude: -87.6278
southcentralus:
  name: South Central US
  latitude: 29.4167
  longitude: -98.5
eastus:
  name: East US
  latitude: 37.3719
  longitude: -79.8164
eastus2:
  name: East US 2
  latitude: 36.6681
  longitude: -78.3889
uksouth:
  name: UK South
  latitude: 50.941
  longitude: -0.799
ukwest:
  name: UK West
  latitude: 53.427
  longitude: -3.084
westeurope:
  name: West Europe
  latitude: 52.3667
  longitude: 4.9
northeurope:
  name: North Europe
  latitude: 53.3478
  longitude: -6.2597
japaneast:
  name: Japan East
  latitude: 35.68
  longitude: 139.77
japanwest:
  name: Japan West
  latitude: 34.6939
  longitude: 135.5022
eastasia:
  name: East Asia
  latitude: 22.267
  longitude: 114.188
southeastasia:
  name: Southeast Asia
  latitude: 1.283
  longitude: 103.833
australiacentral:
  name: Australia Central
  latitude: -35.3075
  longitude: 149.1244
australiaeast:
  name: Australia East
  latitude: -33.86
  longitude: 151.2094
australiasoutheast:
  name: Australia Southeast
  latitude: -37.8136
  longitude: 144.9631
francecentral:
  name: France Central
  latitude: 46.3772
  longitude: 2.3730
southafricanorth:
  name: South Africa North
  latitude: -25.731340
  longitude: 28.218370
centralindia:
  name: Central India
  latitude: -25.731340
  longitude: 28.218370
southindia:
  name: South India
  latitude: 12.9822
  longitude: 80.1636
westindia:
  name: West India
  latitude: 19.088
  longitude: 72.868
koreacentral:
  name: Korea Central
  latitude: 37.5665
  longitude: 126.9780
koreasouth:
  name: Korea South
  latitude: 35.1796
  longitude: 129.0756
canadacentral:
  name: Canada Central
  latitude: 43.653
  longitude: -79.383
canadaeast:
  name: Canada East
  latitude: 46.817
  longitude: -71.217
germanywestcentral:
  name: Germany West Central
  latitude: 50.110924
  longitude: 8.682127
norwayeast:
  name: Norway East
  latitude: 59.913868
  longitude: 10.752245
switzerlandnorth:
  name: Switzerland North
  latitude: 47.451542
  longitude: 8.564572
uaenorth:
  name: UAE North
  latitude: 25.266666
  longitude: 55.316666
brazilsouth:
  name: Brazil South
  latitude: -23.55
  longitude: -46.633
