# Copyright (c) YugaByte, Inc.
africa-south1:
  name: Johannesburg, South Africa
  latitude: 26.2056
  longitude:  28.0337
  availabilty_zones: [africa-south1-a, africa-south1-b, africa-south1-c]
asia-east1:
  name: Taiwan
  latitude: 23.9919519
  longitude: 120.3300829
  availabilty_zones: [asia-east1-a, asia-east1-b, asia-east1-c]
asia-east2:
  name: Hong Kong
  latitude: 22.319304
  longitude: 114.169361
  availabilty_zones: [asia-east2-a, asia-east2-b, asia-east2-c]
asia-southeast1:
  name: Singapore
  latitude: 1.352083
  longitude: 103.819836
  availabilty_zones: [asia-southeast1-a, asia-southeast1-b, asia-southeast1-c]
asia-southeast2:
  name: Jakarta
  latitude: -6.208763
  longitude: 106.845599
  availabilty_zones: [asia-southeast2-a, asia-southeast2-b, asia-southeast2-c]
asia-northeast1:
  name: Tokyo
  latitude: 35.689488
  longitude: 139.691706
  availabilty_zones: [asia-northeast1-a, asia-northeast1-b, asia-northeast1-c]
asia-northeast2:
  name: Osaka
  latitude: 34.693725
  longitude: 135.502254
  availabilty_zones: [asia-northeast2-a, asia-northeast2-b, asia-northeast2-c]
asia-northeast3:
  name: Seoul
  latitude: 37.566535
  longitude: 126.977969
  availabilty_zones: [asia-northeast3-a, asia-northeast3-b, asia-northeast3-c]
asia-south1:
  name: Mumbai
  latitude: 19.0825223
  longitude: 72.7411014
  availabilty_zones: [asia-south1-a, asia-south1-b, asia-south1-c]
asia-south2:
  name: Delhi
  latitude: 28.704059
  longitude: 77.10249
  availabilty_zones: [asia-south2-a, asia-south2-b, asia-south2-c]
us-central1:
  name: Iowa
  latitude: 41.2326957
  longitude: -95.9167207
  availabilty_zones: [us-central1-a, us-central1-b, us-central1-c, us-central1-f]
us-west1:
  name: Oregon
  latitude: 45.6094756
  longitude: -121.2088799
  availabilty_zones: [us-west1-a, us-west1-b, us-west1-c]
us-west2:
  name: California
  latitude: 34.052235
  longitude: -118.243683
  availabilty_zones: [us-west2-a, us-west2-b, us-west2-c]
us-west3:
  name: Utah
  latitude: 40.7608
  longitude: -111.8910
  availabilty_zones: [us-west3-a, us-west3-b, us-west3-c]
us-west4:
  name: Nevada
  latitude: 36.1699
  longitude: -115.1398
  availabilty_zones: [us-west4-a, us-west4-b, us-west4-c]
us-east1:
  name: South Carolina
  latitude: 33.1637261
  longitude: -80.1845003
  availabilty_zones: [us-east1-b, us-east1-c, us-east1-d]
us-east4:
  name: Northern Virginia
  latitude: 39.0300218
  longitude: -77.5121424
  availabilty_zones: [us-east4-a, us-east4-b, us-east4-c]
us-east5:
  name: Ohio
  latitude: 39.983334
  longitude: -82.983330
  availabilty_zones: [us-east5-a, us-east5-b, us-east5-c]
us-south1:
  name: Texas
  latitude: 32.779167
  longitude: -96.808891
  availabilty_zones: [us-south1-a, us-south1-b, us-south1-c]
northamerica-northeast1:
  name: Montreal
  latitude: 45.5581968
  longitude: -73.8703852
  availabilty_zones: [northamerica-northeast1-a, northamerica-northeast1-b, northamerica-northeast1-c]
northamerica-northeast2:
  name: Toronto
  latitude: 43.653226
  longitude: -79.383184
  availabilty_zones: [northamerica-northeast2-a, northamerica-northeast2-b, northamerica-northeast2-c]
southamerica-east1:
  name: Sao Paulo
  latitude: -23.286926
  longitude: -46.627497
  availabilty_zones: [southamerica-east1-a, southamerica-east1-b, southamerica-east1-c]
southamerica-west1:
  name: Chile
  latitude: 35.6751
  longitude: 71.5430
  availabilty_zones: [southamerica-west1-a, southamerica-west1-b, southamerica-west1-c]
europe-central2:
  name: Poland
  latitude: 52.229676
  longitude: 21.012229
  availabilty_zones: [europe-central2-a, europe-central2-b, europe-central2-c]
europe-southwest1:
  name: Spain
  latitude: 40.4637
  longitude: 3.7492
  availabilty_zones: [europe-southwest1-a, europe-southwest1-b, europe-southwest1-c]
europe-west1:
  name: Belgium
  latitude: 50.489824
  longitude: 3.7378805
  availabilty_zones: [europe-west1-b, europe-west1-c, europe-west1-d]
europe-west10:
  name: Germany
  latitude: 51.1657
  longitude: 10.4515
  availabilty_zones: [europe-west10-a, europe-west10-b, europe-west10-c]
europe-west12:
  name: Turin, Italy
  latitude: 41.8719
  longitude: 12.5674
  availabilty_zones: [europe-west12-a, europe-west12-b, europe-west12-c]
europe-west2:
  name: London
  latitude: 51.500152
  longitude: -0.126236
  availabilty_zones: [europe-west2-a, europe-west2-b, europe-west2-c]
europe-west3:
  name: Frankfurt
  latitude: 50.111512
  longitude: 8.680506
  availabilty_zones: [europe-west3-a, europe-west3-b, europe-west3-c]
europe-west4:
  name: Netherlands
  latitude: 53.4356948
  longitude: 6.7980783
  availabilty_zones: [europe-west4-a, europe-west4-b, europe-west4-c]
europe-west6:
  name: Switzerland
  latitude: 47.376887
  longitude: 8.541694
  availabilty_zones: [europe-west6-a, europe-west6-b, europe-west6-c]
europe-west8:
  name: Milan, Italy
  latitude: 41.8719
  longitude: 12.5674
  availabilty_zones: [europe-west8-a, europe-west8-b, europe-west8-c]
europe-west9:
  name: France
  latitude: 46.2276
  longitude: 2.2137
  availabilty_zones: [europe-west9-a, europe-west9-b, europe-west9-c]
europe-north1:
  name: Finland
  latitude: 60.5695912
  longitude: 27.2097431
  availabilty_zones: [europe-north1-a, europe-north1-b, europe-north1-c]
australia-southeast1:
  name: Sydney
  latitude: -33.867139
  longitude: 151.207114
  availabilty_zones: [australia-southeast1-a, australia-southeast1-b, australia-southeast1-c]
australia-southeast2:
  name: Melbourne
  latitude:  -37.813628
  longitude: 144.963058
  availabilty_zones: [australia-southeast2-a, australia-southeast2-b, australia-southeast2-c]
me-central1:
  name: Qatar
  latitude:  25.3548
  longitude: 51.1839
  availabilty_zones: [me-central1-a, me-central1-b, me-central1-c]
me-central2:
  name: Saudi Arabia
  latitude:  23.8859
  longitude: 45.0792
  availabilty_zones: [me-central2-a, me-central2-b, me-central2-c]
me-west1:
  name: Israel
  latitude:  31.0461
  longitude: 34.8516
  availabilty_zones: [me-west1-a, me-west1-b, me-west1-c]
