# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

air_gap: false
install_dev_packages: false
install_backup_packages: "{{ cloud_type != 'onprem' }}"
update_yum_cache: false
yum_retry_count: 5

linux_packages: []

backup_packages:
  - s3cmd

backup_gcloud_package: google-cloud-sdk-286.0.0-linux-x86_64.tar.gz
backup_gcloud_components:
  - gsutil

backup_azcopy_src: https://azcopyvnext.azureedge.net/release20200410/azcopy_linux_amd64_10.4.0.tar.gz

dev_packages:
  - emacs
  - gdb
  - iotop
  - python-pip
  - python-psutil
  - rsync
  - sysstat
  - traceroute
  - vim

debian_packages:
  - libboost-dev
  - libboost-system-dev
  - libboost-thread-dev
  - libcrcutil-dev
  - liboauth-dev
  - libsasl2-dev
  - libunwind-dev

redhat_packages:
  - boost
  - boost-devel
  - boost-static
  - boost-system
  - boost-thread
  - lsof
  - cyrus-sasl-devel
  - cyrus-sasl-plain
  - liboauth
  - policycoreutils-python
  # Mobile shell that supports roaming and intelligent local echo. This may
  # be useful for logging into servers remotely at some point.
  - mosh
  - bind-utils  # For nslookup.
  - wget
  - file  # A utility for determining file type.
  - libselinux-python
  - atop
  - perf
  - python-devel

azure_packages:
  - libselinux-python
