# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- name: Confirm target is present
  assert:
    that:
      - instance_name is defined
      - private_ip is defined
      - cloud_region is defined
      - cloud_subnet is defined

- name: Select target instance
  ec2_instance_facts:
    region: "{{ cloud_region }}"
    filters:
      instance-state-name: ["running", "stopped"]
      "tag:Name": "{{ instance_name }}"
      private-ip-address: "{{ private_ip }}"
      # Don't really need this, if the name is guaranteed unique.
      subnet-id: "{{ cloud_subnet }}"
  register: ec2_instances

- name: Destroy target instance
  ec2:
    region: "{{ cloud_region }}"
    instance_ids: "{{ ec2_instances.instances | map(attribute='instance_id') | list }}"
    state: absent
  when: ec2_instances.instances is defined and ec2_instances.instances | length >  0
