services:
  - name: prometheusConfig
    fileName: "{{ .ConfFileLocation }}"
    contents: |
      # Copyright (c) YugabyteDB, Inc.

      global:
        # By default, scrape targets every 15 seconds.
        scrape_interval:     {{ yamlPath "prometheus.scrapeInterval" }}
        evaluation_interval: {{ yamlPath "prometheus.scrapeInterval" }}
        scrape_timeout: {{ yamlPath "prometheus.scrapeTimeout" }}

        # The labels to add to any time series or alerts when communicating with
        # external systems (federation, remote storage, Alertmanager).
        external_labels:
          monitor: 'swamper'
      {{- if eq (yamlPath "prometheus.remoteWrite.enabled") "true" }}
      remote_write:
      {{- toYaml "prometheus.remoteWrite.configs" | nindent 6}}
      {{- end }}

      rule_files:
      - '{{ .DataDir }}/swamper_rules/yugaware.ad.*.yml'
      - '{{ .DataDir }}/swamper_rules/yugaware.recording-rules.yml'

      # A list of scrape configurations.
      scrape_configs:

      - job_name: 'prometheus'
        scrape_interval: {{ yamlPath "prometheus.scrapeInterval" }}
        scrape_timeout:  {{ yamlPath "prometheus.scrapeTimeout" }}
        {{ if eq (yamlPath "prometheus.enableHttps") "true" }}
        scheme: https
        tls_config:
          insecure_skip_verify: true
        {{ end }}
        {{ if eq (yamlPath "prometheus.enableAuth") "true" }}
        basic_auth:
          username: {{ yamlPath "prometheus.authUsername" }}
          password: {{ yamlPath "prometheus.authPassword" }}
        {{ end }}
        static_configs:
          - targets: ['{{ index (splitInput (yamlPath "host")) 0 }}:{{ yamlPath "prometheus.port" }}']

      - job_name: 'platform'
        scheme: https
        tls_config:
          insecure_skip_verify: true
        scrape_timeout:  {{ yamlPath "prometheus.scrapeTimeout" }}
        metrics_path: "/api/v1/prometheus_metrics"
        static_configs:
          - targets: ['{{ index (splitInput (yamlPath "host")) 0 }}:{{ yamlPath "platform.port" }}']

      - job_name: 'node-agent'
        scrape_timeout:  {{ yamlPath "prometheus.scrapeTimeout" }}
        scheme: {{ yamlPath "prometheus.scrapeConfig.node-agent.scheme" }}
        metrics_path: "/metrics"
        file_sd_configs:
          - files:
            - '{{ .DataDir }}/swamper_targets/node-agent.*.json'

      - job_name: 'otel-collector'
        scrape_timeout:  {{ yamlPath "prometheus.scrapeTimeout" }}
        scheme: {{ yamlPath "prometheus.scrapeConfig.otel-collector.scheme" }}
        metrics_path: "/metrics"
        file_sd_configs:
          - files:
              - '{{ .DataDir }}/swamper_targets/otel.*.json'

      - job_name: "node"
        scheme: {{ yamlPath "prometheus.scrapeConfig.node.scheme" }}
        file_sd_configs:
          - files:
            - '{{ .DataDir }}/swamper_targets/node.*.json'
        metric_relabel_configs:
        # Below relabels are required for smooth migration from node_exporter 0.13.0 to latest
        - source_labels: ["__name__"]
          regex: "node_cpu"
          target_label: "__name__"
          replacement: "node_cpu_seconds_total"
        - source_labels: ["__name__"]
          regex: "node_filesystem_free"
          target_label: "__name__"
          replacement: "node_filesystem_free_bytes"
        - source_labels: ["__name__"]
          regex: "node_filesystem_size"
          target_label: "__name__"
          replacement: "node_filesystem_size_bytes"
        - source_labels: ["__name__"]
          regex: "node_disk_reads_completed"
          target_label: "__name__"
          replacement: "node_disk_reads_completed_total"
        - source_labels: ["__name__"]
          regex: "node_disk_writes_completed"
          target_label: "__name__"
          replacement: "node_disk_writes_completed_total"
        - source_labels: ["__name__"]
          regex: "node_memory_MemTotal"
          target_label: "__name__"
          replacement: "node_memory_MemTotal_bytes"
        - source_labels: ["__name__"]
          regex: "node_memory_Slab"
          target_label: "__name__"
          replacement: "node_memory_Slab_bytes"
        - source_labels: ["__name__"]
          regex: "node_memory_Cached"
          target_label: "__name__"
          replacement: "node_memory_Cached_bytes"
        - source_labels: ["__name__"]
          regex: "node_memory_Buffers"
          target_label: "__name__"
          replacement: "node_memory_Buffers_bytes"
        - source_labels: ["__name__"]
          regex: "node_memory_MemFree"
          target_label: "__name__"
          replacement: "node_memory_MemFree_bytes"
        - source_labels: ["__name__"]
          regex: "node_network_receive_bytes"
          target_label: "__name__"
          replacement: "node_network_receive_bytes_total"
        - source_labels: ["__name__"]
          regex: "node_network_transmit_bytes"
          target_label: "__name__"
          replacement: "node_network_transmit_bytes_total"
        - source_labels: ["__name__"]
          regex: "node_network_receive_packets"
          target_label: "__name__"
          replacement: "node_network_receive_packets_total"
        - source_labels: ["__name__"]
          regex: "node_network_transmit_packets"
          target_label: "__name__"
          replacement: "node_network_transmit_packets_total"
        - source_labels: ["__name__"]
          regex: "node_network_receive_errs"
          target_label: "__name__"
          replacement: "node_network_receive_errs_total"
        - source_labels: ["__name__"]
          regex: "node_network_transmit_errs"
          target_label: "__name__"
          replacement: "node_network_transmit_errs_total"
        - source_labels: ["__name__"]
          regex: "node_disk_bytes_read"
          target_label: "__name__"
          replacement: "node_disk_read_bytes_total"
        - source_labels: ["__name__"]
          regex: "node_disk_bytes_written"
          target_label: "__name__"
          replacement: "node_disk_written_bytes_total"
        - source_labels: ["__name__"]
          regex: "node_boot_time"
          target_label: "__name__"
          replacement: "node_boot_time_seconds"
        # saved_name relabel goes last to get correct label names after above relabels
        - source_labels: ["__name__"]
          regex: "(.*)"
          target_label: "saved_name"
          replacement: "$1"

      - job_name: "yugabyte"
        scheme: {{ yamlPath "prometheus.scrapeConfig.yugabyte.scheme" }}
        tls_config:
            insecure_skip_verify: true
        metrics_path: "/prometheus-metrics"
        file_sd_configs:
          - files:
            - '{{ .DataDir }}/swamper_targets/yugabyte.*.json'
        metric_relabel_configs:
        - source_labels: ["__name__"]
          regex: "(.*)"
          target_label: "saved_name"
          replacement: "$1"
        - source_labels: ["__name__"]
          regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)"
          target_label: "server_type"
          replacement: "$1"
        - source_labels: ["__name__"]
          regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)"
          target_label: "service_type"
          replacement: "$2"
        - source_labels: ["__name__"]
          regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?"
          target_label: "service_method"
          replacement: "$3"
        - source_labels: ["__name__"]
          regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?"
          target_label: "__name__"
          replacement: "rpc_latency$4"

  - name: prometheusService
    fileName: "{{ .SystemdFileLocation }}"
    contents: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      {{ if eq (yamlPath "as_root") "true" }}
      User={{ yamlPath "service_username" }}
      Group={{ yamlPath "service_username" }}
      {{ end }}
      Type=simple
      ExecStart= /bin/sh -c "{{ .PromDir }}/prometheus \
      --config.file {{ .ConfFileLocation }} \
      --storage.tsdb.path {{ .DataDir }}/storage \
      --storage.tsdb.retention.time={{ yamlPath "prometheus.retentionTime" }} \
      --web.console.templates={{ .PromDir }}/consoles \
      --web.console.libraries={{ .PromDir }}/console_libraries \
      --web.enable-admin-api \
      --web.enable-lifecycle \
      --web.enable-remote-write-receiver \
      --web.config.file={{ .WebConfFile }} \
      --web.listen-address=:{{ yamlPath "prometheus.port" }} \
      --query.max-concurrency={{ yamlPath "prometheus.maxConcurrency" }} \
      --query.max-samples={{ yamlPath "prometheus.maxSamples" }} \
      --query.timeout={{ yamlPath "prometheus.timeout" }} >> {{ .LogDir }}/prometheus.log 2>&1"

      Restart=always
      RestartSec={{ yamlPath "prometheus.restartSeconds"}}
      OOMScoreAdjust={{ yamlPath "prometheus.oomScoreAdjust"}}

      [Install]
      WantedBy=multi-user.target

  - name: prometheusWebConf
    fileName: "{{ .WebConfFile }}"
    contents: |
      {{ if eq (yamlPath "prometheus.enableHttps") "true" }}
      {{ $tlsCiphers := yamlPathSlice "prometheus.allowedTLSCiphers" }}
      tls_server_config:
        cert_file: {{ .HttpsCertPath }}
        key_file: {{ .HttpsKeyPath }}
        {{ if gt (len $tlsCiphers) 0 }}
        cipher_suites:
          {{ range $suite :=  $tlsCiphers }}
          - {{ removeQuotes $suite }}
          {{ end }}
        {{ end }}
      {{ end }}
  - name: prometheusLogrotate
    fileName: "{{ logrotateD }}/prometheus"
    contents: |
      {{ .LogDir }}/prometheus.log {
          daily
          rotate 7
          compress
          missingok
          notifempty
          copytruncate
          delaycompress
          create 0640 {{ yamlPath "service_username" }} {{ yamlPath "service_username" }}
      }
