description: |
  ConfigureMetricsExportReq

  Payload to configure metrics export. Part of
  ConfigureMetricsExportReq
x-yba-api-since: 2025.2.0.0
x-yba-api-visibility: preview
required: false
content:
  application/json:
    schema:
      $ref: "../schemas/ConfigureMetricsExportSpec.yaml"
