# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

dependencies:
  - role: ansible-prometheus
    become: yes
    become_method: sudo
    prometheus_go_version: 1.7
    prometheus_use_service: true
    prometheus_node_exporter_opts: "-web.listen-address=:{{ node_exporter_port }}"
    prometheus_node_exporter_use_systemd: true
    when: install_node_exporter is not defined or install_node_exporter|bool
