author = "Team Yugabyte"
description = "YugabyteDB, the transactional, high-performance database for building internet-scale, globally-distributed apps."
copyright = "Yugabyte, Inc."
privacy_policy = "https://www.yugabyte.com/privacy-policy/"
kapa_ai = true
drift_snippet = true
search_banner = true
version_menu = "Releases"

# Change version_menu_pagelinks to true to go to the same page when you switch
# versions from the dropdown menu.
version_menu_pagelinks = true

[search]
  algolia_docsearch = true
  algolia_sequence_expressions = true

[path_base_for_github_subdir]
  from = "content/en/(.*?)/"
  to = "content/$1/"

[[links.developer]]
  name = "Slack"
  url = "https://communityinviter.com/apps/yugabyte-db/register"
  icon = "fab fa-slack"

[[links.developer]]
  name = "GitHub"
  url = "https://github.com/yugabyte/yugabyte-db"
  icon = "fab fa-github"

[[links.developer]]
  name = "Twitter"
  url = "https://twitter.com/yugabyte"
  icon = "fab fa-twitter"

[[links.developer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/yugabyte"
  icon = "fab fa-linkedin"

[[links.developer]]
  name = "YouTube"
  url = "https://www.youtube.com/channel/UCL9BhSLRowqQ1TyBndhiCEw"
  icon = "fab fa-youtube"

[ui]
  sidebar_cache_limit = 25000
  navbar_logo = true
  sidebar_menu_compact = true
  sidebar_menu_foldable = true
  sidebar_search_disable = true
  ul_show = 1

[[versions]]
  url = "/stable"
  version = "v2024.1 (STS)"
[[versions]]
  url = "/preview"
  version = "v2.21 (Preview)"
[[versions]]
  url = "/v2.20"
  version = "v2.20 (LTS)"
[[versions]]
  url = "/v2.18"
  version = "v2.18 (STS)"
[[versions]]
  url = "/v2.14"
  version = "v2.14 (LTS)"
[[versions]]
  url = "https://docs-archive.yugabyte.com/v2.16"
  version = "Unsupported versions"
  newTab = true

# Custom params, regardless of theme
[yb]
  terms_of_service = "https://www.yugabyte.com/terms-of-service/"
  preview_version = "v2.21"
  preview_version_slug = "stable"
  # To disable heading/title icons for particular page, define `hideHeadingIcon: true` on that page params.
  heading_icons = true

# Header logo link
[yb.navbar_logo]
  path = "/images/yugabytedb-logo.svg"
  url = "/"
  title = "YugabyteDB"
# Footer logo link
[yb.footer_logo]
  path = "/images/yugabytedb-logo.svg"
  url = "/"
  title = "YugabyteDB"
