os:
    - linux

sudo: required
dist: trusty

language: c

services:
    - docker

install:
    - sed -e 's/${CHECK_CODE}/'${CHECK_CODE}/g -e 's/${PG_VERSION}/'${PG_VERSION}/g Dockerfile.tmpl > Dockerfile
    - docker-compose build

script:
    - docker-compose run tests

env:
    - PG_VERSION=10      CHECK_CODE=clang
    - PG_VERSION=10      CHECK_CODE=cppcheck
    - PG_VERSION=10      CHECK_CODE=false
    - PG_VERSION=11      CHECK_CODE=clang
    - PG_VERSION=11      CHECK_CODE=false
    - PG_VERSION=12      CHECK_CODE=clang
    - PG_VERSION=12      CHECK_CODE=false
    - PG_VERSION=13      CHECK_CODE=clang
    - PG_VERSION=13      CHECK_CODE=false
    - PG_VERSION=14      CHECK_CODE=clang
    - PG_VERSION=14      CHECK_CODE=false
    - PG_VERSION=15      CHECK_CODE=clang
    - PG_VERSION=15      CHECK_CODE=false
