# Copyright (c) YugaByte, Inc.

us-east-1:
  name: "US East (N. Virginia)"
  latitude: 38.8048
  longitude: -77.0469

us-east-2:
  name: "US East (Ohio)"
  latitude: 39.9612
  longitude: -82.9988

us-west-1:
  name: "US West (N. California)"
  latitude: 37.7749
  longitude: -122.4194

us-west-2:
  name: "US West (Oregon)"
  latitude: 45.5051
  longitude: -122.6750

ap-east-1:
  name: "Asia Pacific (Hong Kong)"
  latitude: 22.2793
  longitude: 114.1628

ap-northeast-1:
  name: "Asia Pacific (Tokyo)"
  latitude: 35.6762
  longitude: 139.6503

ap-northeast-2:
  name: "Asia Pacific (Seoul)"
  latitude: 37.5665
  longitude: 126.9780

ap-northeast-3:
  name: "Asia Pacific (Osaka-Local)"
  latitude: 34.6937
  longitude: 135.5022

ap-south-1:
  name: "Asia Pacific (Mumbai)"
  latitude: 19.0760
  longitude: 72.8777

ap-south-2:
  name: Asia Pacific (Hyderabad)
  latitude: 17.3850
  longitude: 78.4867

ap-southeast-1:
  name: "Asia Pacific (Singapore)"
  latitude: 1.3521
  longitude: 103.8198

ap-southeast-2:
  name: "Asia Pacific (Sydney)"
  latitude: -33.8688
  longitude: 151.2093

ap-southeast-3:
  name: Asia Pacific (Jakarta)
  latitude: -6.200000
  longitude: 106.816666

ca-central-1:
  name: "Canada (Central)"
  latitude: 45.5017
  longitude: -73.5673

eu-central-1:
  name: "EU (Frankfurt)"
  latitude: 50.1109
  longitude: 8.6821

eu-north-1:
  name: "EU (Stockholm)"
  latitude: 59.3293
  longitude: 18.0686

eu-south-1:
  name: "EU (Milan)"
  latitude: 45.4654
  longitude: 9.1859

eu-west-1:
  name: "EU (Ireland)"
  latitude: 53.3498
  longitude: -6.2603

eu-west-2:
  name: "EU (London)"
  latitude: 51.5074
  longitude: -0.1278

eu-west-3:
  name: "EU (Paris)"
  latitude: 48.8566
  longitude: 2.3522

me-south-1:
  name: "Middle East (Bahrain)"
  latitude: 26.0667
  longitude: 50.5577

sa-east-1:
  name: "South America (Sao Paulo)"
  latitude: -23.5505
  longitude: -46.6333

af-south-1:
  name: "Africa (Cape Town)"
  latitude: -33.92
  longitude: 18.42
