version: "3.3"
services:
  db:
    image: apache/age:dev_snapshot_PG15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=agens
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
