# Copyright 2019 YugaByte, Inc. and Contributors
#
# Licensed under the Polyform Free Trial License 1.0.0 (the "License"); you
# may not use this file except in compliance with the License. You
# may obtain a copy of the License at
#
# https://github.com/YugaByte/yugabyte-db/blob/master/licenses/POLYFORM-FREE-TRIAL-LICENSE-1.0.0.txt

- assert:
    that:
      - process_types is defined
      - user_name is defined
      - placement_cloud is defined
      - placement_region is defined
      - placement_zone is defined
      - mount_points is defined
      - systemd_option is defined
      - yb_num_clean_cores_to_keep is defined

- name: Prepare host
  include: "prepare-configure-server.yml"

- name: "Set up {{ yb_process_type }}"
  include: "configure-process-type.yml"
  with_items: "{{ process_types }}"
  loop_control:
    loop_var: yb_process_type
