name: <universe-name>
provider-code: <provider-code>
provider-name: <provider-name>
yb-db-version: <YugabyteDB-version>
# add-read-replica: true
replication-factor:
  - 1 # represents primary cluster replication factor
  - 3 # represents read replica replication factor
num-nodes:
  - 1
  - 3
user-tags:
  <key-1>: <value-1>
  <key-2>: <value-2>
  <key-3>: <value-3>
master-gflags:
  gflag-1: value-1
  gflag-2: value-2
  gflag-3: value-3
tserver-gflags:
  primary:
    gflag-1: "value-1"
    gflag-2: "value-2"
  async:
    gflag-1: "value-1"
    gflag-2: "value-2"
