---
baseurl: https://docs.yugabyte.com
languageCode: en-us
title: YugabyteDB Docs
metadataformat: yaml
googleAnalytics: UA-104956980-3
pygmentsCodefences: true
pygmentsStyle: "pygments"
enableGitInfo: true
resourceDir: docs/resources

frontmatter:
  date:
    - :git
    - :default

params:
  author: Team Yugabyte
  description: 'YugabyteDB, the transactional, high-performance database for building internet-scale, globally-distributed apps.'
  copyright: 'Yugabyte, Inc.'
  block_indexing: false
  version: Beta
  logo: /images/og-image.jpg
  favicon: /images/favicon.ico
  permalink: '#'
  custom_css: []
  custom_js: []
  highlight_css: css/highlight/hemisu.css
  palette:
    primary: orange
    accent: amber
  font:
    text: Source Sans Pro
    code: Inconsolata
  algolia:
    index: yugabyte
    appID: UMBCUJCBE8
    apiKey: 1e8f71f988a4165eca695c63aeed7bee
  bigpicture:
    projectId: 1064
  ui:
    # https://github.com/gohugoio/hugo/issues/8918#issuecomment-903314696
    sidebar_cache_limit: 1
social: {}
menu:
  main:
    - name: Introduction
      identifier: intro
markup:
  goldmark:
    extensions:
      typographer: false
    parser:
      autoHeadingIDType: blackfriday
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 3
    ordered: false
---
