name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - 'docs/**'

  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md
      - 'docs/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04
    name: ${{ matrix.name }}

    # Grab the latest CentOS 7 image from here:
    # https://hub.docker.com/r/yugabyteci/yb_build_infra_centos7/tags?page=1&ordering=last_updated

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "GCC 5, debug, Linuxbrew, CentOS 7"
            os: ubuntu-20.04
            yb_build_args: debug
          - name: "GCC 5, release, Linuxbrew, CentOS 7"
            os: ubuntu-20.04
            yb_build_args: release
          - name: "Clang 11, debug, CentOS 7"
            os: ubuntu-20.04
            yb_build_args: --clang11 debug
          - name: "Clang 11, release, CentOS 7"
            os: ubuntu-20.04
            yb_build_args: --clang11 release
    if: >
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'skip ci') &&
       !contains(github.event.head_commit.message, 'ci skip')) ||
      github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v2

      - name: Build YugabyteDB
        run: |
          echo "OSTYPE (outside Docker): $OSTYPE"
          echo "Build name: ${{ matrix.name }}"
          echo "Docker image: ${{ matrix.docker_image }}"
          if [[ $OSTYPE == linux* ]]; then
            build_dir_in_container=/opt/yb-build/yugabyte-db
            docker run \
              -i \
              "-w=$build_dir_in_container" \
              --mount type=bind,source="$PWD",target="$build_dir_in_container" \
              "yugabyteci/yb_build_infra_centos7:v2021-03-26T05_02_29" \
              bash -c '
                set -euo pipefail -x
                echo "OSTYPE (inside Docker): $OSTYPE"
                echo "PATH: $PATH"
                export PATH=/usr/local/bin:$PATH
                ( set -x; ls -l /usr/local/bin )
                set +e
                ( set -x; which ninja )
                ( set -x; which cmake )
                set -e
                chown -R yugabyteci .
                sudo -u yugabyteci bash -c "
                  set -euo pipefail
                  export PATH=/usr/local/bin:\$PATH
                  df -H /
                  echo ::group::Building YugabyteDB
                  ./yb_build.sh release --download-thirdparty --ninja ${{ matrix.yb_build_args }}
                  echo ::endgroup::
                  df -H /
                "
              '
          elif [[ $OSTYPE == darwin* ]]; then
            system_profiler SPSoftwareDataType
            sw_vers
            ./yb_build.sh release
          fi
