name: Go Driver Tests

on:
  push:
    branches: [ "master", "PG11" ]

  pull_request:
    branches: [ "master", "PG11" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19' ]
    defaults:
      run:
        working-directory: drivers/golang/age/
  
    steps:
    - uses: actions/checkout@v3

    - name: Set tag based on branch
      run: |
        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == "refs/heads/PG11" ]]; then
            echo "TAG=PG11_latest" >> $GITHUB_ENV
          fi
        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          if [[ "$GITHUB_BASE_REF" == "master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "$GITHUB_BASE_REF" == "PG11" ]]; then
            echo "TAG=PG11_latest" >> $GITHUB_ENV
          fi
        fi
      
    - name: Run apache/age docker image
      run: |
        export TAG=$TAG
        docker-compose up -d

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test . -v
