name: Go Driver Tests

on:
  push:
    branches: [ "master" ]
    paths: 
      - 'drivers/golang/**'

  pull_request:
    branches: [ "master" ]
    paths: 
      - 'drivers/golang/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.18', '1.19' ]
    defaults:
      run:
        working-directory: drivers/golang/age/
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Run apache/age docker image
      run: docker-compose up -d

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test . -v
