name: JDBC Driver Tests

on:
  push:
    branches: [ "master", "PG13" ]

  pull_request:
    branches: [ "master", "PG13" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: drivers/jdbc

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set tag based on branch
      run: |
        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == "refs/heads/PG13" ]]; then
            echo "TAG=PG13_latest" >> $GITHUB_ENV
          fi
        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          if [[ "$GITHUB_BASE_REF" == "master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "$GITHUB_BASE_REF" == "PG13" ]]; then
            echo "TAG=PG13_latest" >> $GITHUB_ENV
          fi
        fi

    - name: Build and Test
      run: |
        export TAG=$TAG
        gradle build
