name: Nodejs Driver Tests

on:
  push:
    branches: [ "master", "PG11" ]

  pull_request:
    branches: [ "master", "PG11" ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: drivers/nodejs/
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Set tag based on branch
      run: |
        if [[ "$GITHUB_EVENT_NAME" == "push" ]]; then
          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == "refs/heads/PG11" ]]; then
            echo "TAG=PG11_latest" >> $GITHUB_ENV
          fi
        elif [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          if [[ "$GITHUB_BASE_REF" == "master" ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ "$GITHUB_BASE_REF" == "PG11" ]]; then
            echo "TAG=PG11_latest" >> $GITHUB_ENV
          fi
        fi
      
    - name: Run apache/age docker image
      run: |
        export TAG=$TAG
        docker-compose up -d

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: latest

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Test
      run: npm test