name: SQL Tests
run-name: ${{ github.event.pull_request.title || '' }}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'docs/**'
      - '.devcontainer/**'
      - '*.md'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'docs/**'
      - '.devcontainer/**'
      - '*.md'

jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install package dependencies
        run: |
          # Create the file repository configuration:
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main 16" > /etc/apt/sources.list.d/pgdg.list'
          # Import the repository signing key:
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
          wget \
          curl \
          sudo \
          gnupg2 \
          lsb-release \
          tzdata \
          build-essential \
          pkg-config \
          cmake \
          git \
          postgresql-16 \
          postgresql-server-dev-16 \
          libpq-dev \
          postgresql-16-cron \
          postgresql-16-pgvector \
          postgresql-16-postgis-3 \
          postgresql-16-rum
          export CLEAN_SETUP=1
          export INSTALL_DEPENDENCIES_ROOT=/tmp/install_setup
          mkdir -p /tmp/install_setup
          cp ./scripts/* /tmp/install_setup
          sudo INSTALL_DEPENDENCIES_ROOT=$INSTALL_DEPENDENCIES_ROOT MAKE_PROGRAM=cmake /tmp/install_setup/install_setup_libbson.sh
          sudo INSTALL_DEPENDENCIES_ROOT=$INSTALL_DEPENDENCIES_ROOT /tmp/install_setup/install_setup_pcre2.sh
          sudo INSTALL_DEPENDENCIES_ROOT=$INSTALL_DEPENDENCIES_ROOT /tmp/install_setup/install_setup_intel_decimal_math_lib.sh
          sudo INSTALL_DEPENDENCIES_ROOT=$INSTALL_DEPENDENCIES_ROOT /tmp/install_setup/install_citus_indent.sh

      - name: Configure, Build and Install HelioDB
        run: |
          make
          sudo make install

      - name: Run Tests
        run: make check

      - name: Citus Indent
        run: |
          citus_indent --check || (echo ""; echo "citus_indent failed, refer to CONTRIBUTING.md on how to use citus_indent"; exit 1)    
